name: build-onekeepalive
on:
  workflow_dispatch:
  push:
    paths:
      - '**.m'
      - '.github/workflows/build-onekeepalive.yml'

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Show Xcode
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-path
      - name: Build fat dylib (arm64 + arm64e)
        run: |
          bash ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OneKeepAlive-dylib
          path: out/OneKeepAlive.dylib
